### ISSUE TITLE
Design Map View Through JavaFX

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#10]
**Description**

- Use JavaFX and FXML to create the visual representation of the DLSU map.

**Tasks**

- [x]  Design the static map layout.
- [x]  Add nodes and edges representing the eateries and paths.
- [x]  (Optional) Implement zoom and pan features for better navigation.
