### ISSUE TITLE
Implement User Selection of Eateries

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#11]
**Description**

- Create a system that allows users to select start and destination eateries.

**Tasks**

- [ ]  Create UI elements (e.g., dropdowns or clickable nodes) for selecting eateries.
- [ ]  Link user selection to the pathfinding algorithm.
- [ ]  Handle invalid or unavailable selections gracefully.
