### ISSUE TITLE
Implement Path Visualization

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#12]
**Description**

- Implement visualization to display the computed shortest path on the DLSU map.

**Tasks**

- [x]  Highlight nodes and edges that are part of the computed path.
- [ ]  (Optional) Add color coding to differentiate visited nodes, optimal path, etc.
- [ ]  Update visualization dynamically for each algorithm.
