### ISSUE TITLE
Compare Algorithm Performance

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#13]
**Description**

- Implement a system to measure the time and memory complexity of each algorithm.

**Tasks**

- [x]  Record time and memory usage for the search algorithms.
- [x]  Store results for different map scenarios.
- [x]  Document findings for later analysis.
