### ISSUE TITLE
Generate Performance Report

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#14]
**Description**

- Create a function to generate a performance report comparing the algorithms, which will be used in the final project report.

**Tasks**

- [x]  Generate a summary of time and memory complexity.
- [x]  Write conclusions on which algorithm is better for each scenario.
- [x]  Visualize results using charts or graphs.
