### ISSUE TITLE
Fill Up README for Documentation

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#18]
**Description**

- Provide detailed instructions for installing, running, and using the application.

**Tasks**

- [ ]  Include system requirements and dependencies.
- [ ]  Provide setup instructions, including how to run the program.
- [ ]  Describe the main features and how to use them.
