### ISSUE TITLE
Choose Pathfinding Algorithms

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#2]
**Description**

- Decide on the pathfinding algorithms that will be implemented, such as BFS, DFS, and A*.

**Tasks**

- [x]  Discuss and shortlist algorithms based on effectiveness.
- [x]  Research pros and cons of each algorithm.
- [x]  Document why certain algorithms are chosen.
