### ISSUE TITLE
Design UI Wireframes

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#3]
**Description**

- Design wireframes of the application using SceneBuilder, focusing on ease of use and interactive features.

**Tasks**

- [x]  Identify different UI components needed for the application.
- [x]  Design the map view and user input forms.
- [x]  Create wireframes for adding/removing eateries.
- [x]  Get feedback from team members.
