### ISSUE TITLE
Develop Graph Data Structures

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#4]
**Description**

- Develop the foundational classes `Node`, `Edge`, and `Graph` to model the DLSU map.

**Tasks**

- [x]  Implement `Node` class.
- [x]  Implement `Edge` class.
- [x]  Implement `Graph` class to connect nodes.
