### ISSUE TITLE
Implement Add Eatery Feature

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#8]
**Description**

- Implement functionality to dynamically add a new eatery to the map, updating both the graphical representation and data structure.

**Tasks**

- [x]  Add new eatery nodes to the graph.
- [ ]  Update the JavaFX UI to show new eateries.
- [x]  Ensure the pathfinding algorithms can handle the updated graph.
