### ISSUE TITLE
Implement Remove Eatery Feature

### ISSUE THREAD

**Issue by EvilConundrum** [EvilConundrum/pathfinding-simulator-using-state-based-models#9]
**Description**

- Implement the ability to remove an existing eatery and update the map and graph accordingly.

**Tasks**

- [x]  Remove eatery nodes from the graph.
- [x]  Update the JavaFX UI.
- [x]  Test the removal feature to ensure pathfinding works with the updated graph.
